/* This file is generated by scripts/generate-article-content-registry.mjs. */
import article0 from '../../../../content/como-investigar-uma-query-lenta-usando-datadog-dbm-e-apm/pt-BR/index.mdx?raw';

import type { Locale } from '@/types/Locale';

export const articleContent: Record<string, Partial<Record<Locale, string>>> = {
  'como-investigar-uma-query-lenta-usando-datadog-dbm-e-apm': {
    'pt-BR': article0,
  },
};
